// Hello, world!
package example:pkg@1.0.0;

use wasi:io/output-stream;
use random;

world test {

}

interface my-interface {
    use random.{one, two};
    use wasi:io/output-stream.{test};

    type my-result = result<u32, stuff>;

    resource my-resource;

    do-something: func(len: u32, s: string) -> option<u32>;

    enum stuff {
        one,
        two,
        three,
    }
}
