// Hello, world!
package example:pkg@1.0.0;

use wasi:io/output-stream;
use random;

world test {

}

interface my-interface {
    type my-result = result<u32, stuff>;

    resource my-resource;

    enum stuff {
        one,
        two,
        three,
    }
}
